# Generated by Django 3.1.2 on 2020-10-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201018_1547'),
        ('instagram', '0002_auto_20201018_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
