# Generated by Django 3.1.2 on 2020-10-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20201019_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
